### PR TITLE
Add info how to customize categories (fixes #88)

### LINKED ISSUE #88: [Features] Categories
Add info how to define categories in report.

### PR DESCRIPTION
**Pull request by Maratori**
As described

### CODE REVIEW

**Comment by baev** [comment]
You can also mention that categories json file can be stored in test resources in case of using allure-maven or allure-gradle plugins

**Comment by Maratori** [comment]
Is there any other cases when it can be placed to resources (or another location)?

**Comment by baev** [comment]
> Is there any other cases when it can be placed to resources (or another location)?

not yet, some improvements are scheduled in the next major release

**Comment by baev** [comment]
👍

**Comment by baev** [comment]
thanks!

**Comment by Maratori** [comment]
You are welcome!

**Pull request merged**
